### ISSUE TITLE
Add `provision securityconfig` sub-command

### ISSUE THREAD

**Issue by sylv-io** [system-transparency/stmgr#14]
Add a sub-command to generate `security_configuration.json`

**Comment by MDr164** [comment]
Should the security config be generated the same way the host config is being generated, e.g. allow to either do it via flags and the TUI tool?

**Comment by sylv-io** [comment]
SGTM :grin:

**Comment by MDr164** [comment]
As diskussed we will add the security config generation into it's own UI but reusing the code of the host config UI. This relies on https://github.com/system-transparency/stmgr/pull/19 to be merged prior.

**Comment by jensdrenhaus** [comment]
https://git.glasklar.is/system-transparency/core/stmgr
