### ISSUE TITLE
stmgr-provision-hostconfig, UX change

### ISSUE THREAD

**Issue by bjoto** [system-transparency/stmgr#18]
Minor request for UX change. Selecting interfaces are clunky.

Today:
Tab down to "interfaces" select interface, select back

Wish:
Remove the interface button, and have a drop-down list similar to network-mode

**Comment by MDr164** [comment]
We also wanted to integrate the security config generation in the tool so I'll see what a good way for these to coexist is and will integrate this change along with it :+1:

**Comment by bjoto** [comment]
Ok!
Note that, we will not have the security config in efivars, so that's not a high prio. If possible, have the security_config tool separately.
