### ISSUE TITLE
Provision: Validate hostconfig

### ISSUE THREAD

**Issue by sylv-io** [system-transparency/stmgr#20]
If you enter invalid data via provision GUI, It will keep the invalid field empty without errors or warnings.

e.g:
Set Network Mode to static and set all IP address to `deadbeef` will generate following host_configuration.json:
`{"version":1,"network_mode":"static","host_ip":"","gateway":"","dns":"", ...`

We should probably validate and return errors during saving, or prevent the saving process at all.

**Comment by MDr164** [comment]
This is now unblocked because https://github.com/system-transparency/stboot/pull/48 got merged.

**Comment by jensdrenhaus** [comment]
https://git.glasklar.is/system-transparency/core/stmgr
