### ISSUE TITLE
Add a subcommand to generate stboot disk image

### ISSUE THREAD

**Issue by sylv-io** [system-transparency/stmgr#28]
At the current state, the [system-transparency](https://github.com/system-transparency/system-transparency) repository uses scripts to create stboot installation as disk or ISO images. They require many build dependencies and are the only part of the build-process, which is not integrated into the tooling.

Golang provides all necessary libraries to implement a solid way to generate disk images. It would reduce the overall build dependencies to Golang and Linux coreutils and make the build environment less dependent on the Linux distribution.
Additional Arguments:
* more control over binary reproducibility
* simpler SBOM support in future
* better integration test support (fewer regressions)
* Linux Distro independent (even macOS could be supported)

**Comment by Foxboron** [comment]
Do you have any libraries in mind for this? I have looked around and I don't see a lot of complete libraries for this.

**Comment by sylv-io** [comment]
We could use [go-diskfs](https://github.com/diskfs/go-diskfs). It runs naively and looks feature-complete for our use-case.
any thoughts?

**Comment by sylv-io** [comment]
only ext4 support is missing. we could either drop support for the disk target installation or switch to squashfs.

**Comment by bjoto** [comment]
@Foxboron I'd ignore all targets but *iso*, which only requires vfat AFAIK.

**Comment by jensdrenhaus** [comment]
https://git.glasklar.is/system-transparency/core/stmgr
